//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMatcherApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMatcherApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: all files in file group(s) .
        /// </summary>
        internal static string AllFilesInGroups {
            get {
                return ResourceManager.GetString("AllFilesInGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} File(s) have been deleted and {1} shortcut(s) have been created. Totally {2} byte(s) have been saved..
        /// </summary>
        internal static string ApplicationSummary {
            get {
                return ResourceManager.GetString("ApplicationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Files Locator.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently scanning {0}....
        /// </summary>
        internal static string CurrentDirectoryUpdate {
            get {
                return ResourceManager.GetString("CurrentDirectoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Name.
        /// </summary>
        internal static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected file length inequality.
        /// </summary>
        internal static string FileLengthDiscrepancyError {
            get {
                return ResourceManager.GetString("FileLengthDiscrepancyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cacnel the searching process, incomplete result will be displayed. Are you sure?.
        /// </summary>
        internal static string FileMatchingToCancel {
            get {
                return ResourceManager.GetString("FileMatchingToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish or cancel the search before applying filter.
        /// </summary>
        internal static string FilterConditions {
            get {
                return ResourceManager.GetString("FilterConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        internal static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gozleme.codeplex.com/documentation.
        /// </summary>
        internal static string OnlineHelpUrl {
            get {
                return ResourceManager.GetString("OnlineHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Search.
        /// </summary>
        internal static string PauseSearch {
            get {
                return ResourceManager.GetString("PauseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the operations? Deletions are not reversible..
        /// </summary>
        internal static string ProceedToApplyDeletion {
            get {
                return ResourceManager.GetString("ProceedToApplyDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the operations? Files too large for recycle bin may be permanently deleted..
        /// </summary>
        internal static string ProceedToApplyRecycling {
            get {
                return ResourceManager.GetString("ProceedToApplyRecycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are going to be deleted. Do you want to proceed?.
        /// </summary>
        internal static string ProceedWithDeletion {
            get {
                return ResourceManager.GetString("ProceedWithDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some folders have been ignored as they are subfolders of others..
        /// </summary>
        internal static string RedudantSearchFolders {
            get {
                return ResourceManager.GetString("RedudantSearchFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid folder path..
        /// </summary>
        internal static string RequestValidFolder {
            get {
                return ResourceManager.GetString("RequestValidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Search.
        /// </summary>
        internal static string ResumeSearch {
            get {
                return ResourceManager.GetString("ResumeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files with totally {1} duplicates in {2:0,000} bytes; {3} files processed out of {4}..
        /// </summary>
        internal static string SearchProgressUpdateFormat {
            get {
                return ResourceManager.GetString("SearchProgressUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search canceled by user before completion, incomplete result displayed..
        /// </summary>
        internal static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        internal static string StatusCleanup {
            get {
                return ResourceManager.GetString("StatusCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search complete..
        /// </summary>
        internal static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused....
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string StatusSearching {
            get {
                return ResourceManager.GetString("StatusSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string VersionClosingBracket {
            get {
                return ResourceManager.GetString("VersionClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Version .
        /// </summary>
        internal static string VersionOpeningBracket {
            get {
                return ResourceManager.GetString("VersionOpeningBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
