//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMatcherApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMatcherApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as excluded folder.
        /// </summary>
        public static string AddAsExcludedFolder {
            get {
                return ResourceManager.GetString("AddAsExcludedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as included folder.
        /// </summary>
        public static string AddAsIncludedFolder {
            get {
                return ResourceManager.GetString("AddAsIncludedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: all files in file group(s) .
        /// </summary>
        public static string AllFilesInGroups {
            get {
                return ResourceManager.GetString("AllFilesInGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} File(s) have been deleted and {1} shortcut(s) have been created. Totally {2} byte(s) have been saved..
        /// </summary>
        public static string ApplicationSummary {
            get {
                return ResourceManager.GetString("ApplicationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Files Finder.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently scanning {0}....
        /// </summary>
        public static string CurrentDirectoryUpdate {
            get {
                return ResourceManager.GetString("CurrentDirectoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Name.
        /// </summary>
        public static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Files Found.
        /// </summary>
        public static string DuplicateFilesFound {
            get {
                return ResourceManager.GetString("DuplicateFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected file length inequality.
        /// </summary>
        public static string FileLengthDiscrepancyError {
            get {
                return ResourceManager.GetString("FileLengthDiscrepancyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cacnel the searching process, incomplete result will be displayed. Are you sure?.
        /// </summary>
        public static string FileMatchingToCancel {
            get {
                return ResourceManager.GetString("FileMatchingToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish or cancel the search before applying filter.
        /// </summary>
        public static string FilterConditions {
            get {
                return ResourceManager.GetString("FilterConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files with at least.
        /// </summary>
        public static string FilterCriterion {
            get {
                return ResourceManager.GetString("FilterCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate MBs.
        /// </summary>
        public static string FilterCriterionTail {
            get {
                return ResourceManager.GetString("FilterCriterionTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterWindowTitle {
            get {
                return ResourceManager.GetString("FilterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string HeaderDirectory {
            get {
                return ResourceManager.GetString("HeaderDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (bytes).
        /// </summary>
        public static string HeaderSize {
            get {
                return ResourceManager.GetString("HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string HeaderState {
            get {
                return ResourceManager.GetString("HeaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Actions.
        /// </summary>
        public static string MiActions {
            get {
                return ResourceManager.GetString("MiActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply.
        /// </summary>
        public static string MiApply {
            get {
                return ResourceManager.GetString("MiApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MiClose {
            get {
                return ResourceManager.GetString("MiClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete selected.
        /// </summary>
        public static string MiDeleteSelected {
            get {
                return ResourceManager.GetString("MiDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unselected.
        /// </summary>
        public static string MiDeleteUnselected {
            get {
                return ResourceManager.GetString("MiDeleteUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MiEdit {
            get {
                return ResourceManager.GetString("MiEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MiFile {
            get {
                return ResourceManager.GetString("MiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filter.
        /// </summary>
        public static string MiFilter {
            get {
                return ResourceManager.GetString("MiFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MiHelp {
            get {
                return ResourceManager.GetString("MiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Online Help.
        /// </summary>
        public static string MiOnlineHelp {
            get {
                return ResourceManager.GetString("MiOnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file location.
        /// </summary>
        public static string MiOpenFileLocation {
            get {
                return ResourceManager.GetString("MiOpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pause search.
        /// </summary>
        public static string MiPauseSearch {
            get {
                return ResourceManager.GetString("MiPauseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick _Representative.
        /// </summary>
        public static string MiPickRepresentative {
            get {
                return ResourceManager.GetString("MiPickRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MiRedo {
            get {
                return ResourceManager.GetString("MiRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Resume search.
        /// </summary>
        public static string MiResumeSearch {
            get {
                return ResourceManager.GetString("MiResumeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string MiSearch {
            get {
                return ResourceManager.GetString("MiSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop.
        /// </summary>
        public static string MiStop {
            get {
                return ResourceManager.GetString("MiStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undelete selected.
        /// </summary>
        public static string MiUndeleteSelected {
            get {
                return ResourceManager.GetString("MiUndeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MiUndo {
            get {
                return ResourceManager.GetString("MiUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MiView {
            get {
                return ResourceManager.GetString("MiView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gozleme.codeplex.com/wikipage?title=How%20to%20use.
        /// </summary>
        public static string OnlineHelpUrl {
            get {
                return ResourceManager.GetString("OnlineHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the operations? Deletions are not reversible..
        /// </summary>
        public static string ProceedToApplyDeletion {
            get {
                return ResourceManager.GetString("ProceedToApplyDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the operations? Files too large for recycle bin may be permanently deleted..
        /// </summary>
        public static string ProceedToApplyRecycling {
            get {
                return ResourceManager.GetString("ProceedToApplyRecycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are going to be deleted. Do you want to proceed?.
        /// </summary>
        public static string ProceedWithDeletion {
            get {
                return ResourceManager.GetString("ProceedWithDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some folders have been ignored as they are subfolders of others..
        /// </summary>
        public static string RedudantSearchFolders {
            get {
                return ResourceManager.GetString("RedudantSearchFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected folders.
        /// </summary>
        public static string RemoveSelectedFolders {
            get {
                return ResourceManager.GetString("RemoveSelectedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid folder path..
        /// </summary>
        public static string RequestValidFolder {
            get {
                return ResourceManager.GetString("RequestValidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files with totally {1} duplicates in {2:0,000} bytes; {3} files processed out of {4}..
        /// </summary>
        public static string SearchProgressUpdateFormat {
            get {
                return ResourceManager.GetString("SearchProgressUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start searching.
        /// </summary>
        public static string StartSearching {
            get {
                return ResourceManager.GetString("StartSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search canceled by user before completion, incomplete result displayed..
        /// </summary>
        public static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        public static string StatusCleanup {
            get {
                return ResourceManager.GetString("StatusCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search complete..
        /// </summary>
        public static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused....
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string StatusSearching {
            get {
                return ResourceManager.GetString("StatusSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates Summary.
        /// </summary>
        public static string SumaryWindowTitle {
            get {
                return ResourceManager.GetString("SumaryWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undelete selected.
        /// </summary>
        public static string UndeleteSelected {
            get {
                return ResourceManager.GetString("UndeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string VersionClosingBracket {
            get {
                return ResourceManager.GetString("VersionClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Version .
        /// </summary>
        public static string VersionOpeningBracket {
            get {
                return ResourceManager.GetString("VersionOpeningBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
