rmdir CcDupResolver.Tests\obj /s /q
rmdir CcDupResolver.Tests\bin /s /q
rmdir CcDupResolver\obj /s /q
rmdir CcDupResolver\bin /s /q
rmdir DeDup.Tests\obj /s /q
rmdir DeDup.Tests\bin /s /q
rmdir DeDup\obj /s /q
rmdir DeDup\bin /s /q
rmdir FileMatcher\obj /s /q
rmdir FileMatcher\bin /s /q
rmdir Logging\obj /s /q
rmdir Logging\bin /s /q