//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMatcherLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMatcherLib.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) found with duplicate copies so far totalling {1} files in {2} bytes..
        /// </summary>
        internal static string DuplicationUpdate {
            get {
                return ResourceManager.GetString("DuplicationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) found so far..
        /// </summary>
        internal static string FilesFoundSoFar {
            get {
                return ResourceManager.GetString("FilesFoundSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) found in total..
        /// </summary>
        internal static string FilesFoundTotal {
            get {
                return ResourceManager.GetString("FilesFoundTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) processed so far..
        /// </summary>
        internal static string FilesProcessedSoFar {
            get {
                return ResourceManager.GetString("FilesProcessedSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-processing: done..
        /// </summary>
        internal static string PostProcessingDone {
            get {
                return ResourceManager.GetString("PostProcessingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-processing: generating duplicate file list....
        /// </summary>
        internal static string PostProcessingGeneratingList {
            get {
                return ResourceManager.GetString("PostProcessingGeneratingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-processing: removing non-duplicate files....
        /// </summary>
        internal static string PostProcessingRemovingSingles {
            get {
                return ResourceManager.GetString("PostProcessingRemovingSingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving files from directory &apos;{0}&apos;....
        /// </summary>
        internal static string ScanningDirectory {
            get {
                return ResourceManager.GetString("ScanningDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning file number {0} &apos;{1}&apos;....
        /// </summary>
        internal static string ScanningFile {
            get {
                return ResourceManager.GetString("ScanningFile", resourceCulture);
            }
        }
    }
}
